# Generated by Django 2.2 on 2020-07-05 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='network',
            new_name='networks',
        ),
    ]
