# Generated by Django 2.2 on 2020-07-05 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0002_auto_20200705_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='networks',
        ),
        migrations.AddField(
            model_name='show',
            name='network',
            field=models.CharField(default='Missing', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Network',
        ),
    ]
